// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaboaezyowwxcsduqxho.supabase.co";
// amazonq-ignore-next-line
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhYm9hZXp5b3d3eGNzZHVxeGhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMDY1OTAsImV4cCI6MjA1NDc4MjU5MH0.ahUl-QmDIsXHVcSrH8wgEkGQicjWTsIM36Dp9Iw7FyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);